// ============================================================
// MAHANA TOURS — "Golden Hour Explorer" Design System
// Data layer: All 45+ tours, images, categories, and content
// ============================================================

// CDN Image URLs
export const IMAGES = {
  // Playa Caracol / Aerials
  heroAerial: "/images/site/hero-aerial.png",
  beachAerial: "/images/site/beach-aerial.png",
  caracolAerial2: "/images/site/beach-aerial.png",
  caracolBeach: "/images/site/beach-aerial.png",
  // Radisson
  radissonAerial: "/images/site/radisson-pool.png",
  radissonPool: "/images/site/radisson-pool.png",
  radissonFront: "/images/site/radisson-pool.png",
  // Surf
  surfAction: "/images/tours/waves-chame.png",
  surfGroup: "/images/tours/surf-foundation.png",
  surfSchool: "/images/tours/surf-center.png",
  surfLesson: "/images/tours/surf-101.png",
  surfSunset: "/images/tours/surf-101.png",
  chameWaves: "/images/tours/waves-chame.png",
  // Vento
  ventoClub: "/images/site/hero-aerial.png",
  // Activities
  islaOtoque: "/images/tours/isla-otoque.png",
  jetSki: "/images/tours/jet-ski.png",
  cascadaFilipinas: "/images/tours/cascada-filipinas.png",
  cascadaChame: "/images/tours/cascada-filipinas.png",
  cascadaCanyon: "/images/tours/cascada-filipinas.png",
  cerroChame: "/images/tours/cerro-chame.png",
  cerroChameHike: "/images/tours/cerro-chame.png",
  whaleWatching: "/images/tours/whale-breach.png",
  whaleBreach: "/images/tours/whale-breach.png",
  kitesurfChame: "/images/tours/kite-surf.png",
  kitesurfAerial: "/images/tours/kite-surf.png",
  kitesurfAction: "/images/tours/kite-surf.png",
  valleAntonWaterfall: "/images/tours/valle-anton.png",
  valleAntonPool: "/images/tours/valle-anton.png",
  sunsetCruise: "/images/tours/sunset-cruise.png",
  fishingBoat: "/images/tours/fishing-boat.png",
  fishingCatch: "/images/tours/fishing-boat.png",
  fishingSport: "/images/tours/fishing-boat.png",
  tubingRiver: "/images/tours/tubing-fun.png",
  tubingGroup: "/images/tours/tubing-fun.png",
  islaBonaCoast: "/images/tours/isla-otoque.png",
  // NEW: Tour-focused hero images
  cerroSunrise: "/images/tours/cerro-chame.png",
  cerroHiker: "/images/tours/cerro-chame.png",
  cerroSunset: "/images/tours/cerro-chame.png",
  cascadaFilipinasNew: "/images/tours/cascada-filipinas.png",
  cascadaJungle: "/images/tours/cascada-filipinas.png",
  islaOtoqueBoat: "/images/tours/isla-otoque.png",
  islaOtoqueCoast: "/images/tours/isla-otoque.png",
  kitesurfPuntaChame: "/images/tours/kite-surf.png",
  kitesurfAerialNew: "/images/tours/kite-surf.png",
  surfLessonPanama: "/images/tours/surf-101.png",
  fishingPanama: "/images/tours/fishing-boat.png",
  fishingMarlin: "/images/tours/fishing-boat.png",
};

// Constants
export const WHATSAPP_NUMBER = "+5076988-4566";
export const WHATSAPP_URL = `https://wa.me/5076988456`;
export const EMAIL = "info@toursmahana.com";
export const PHONE = "+507 6988-4566";
export const INSTAGRAM = "https://instagram.com/toursmahana";
export const FACEBOOK = "https://facebook.com/toursmahana";
export const LOCATION = "Playa Caracol, Punta Chame, Panamá";
export const GOOGLE_MAPS = "https://maps.google.com/?q=Playa+Caracol+Panama";

// ============================================================
// CATEGORIES
// ============================================================
export type CategoryId = "surf-kite" | "acuaticas" | "premium" | "botes-sthamas" | "botes-rampage" | "eco-adventures";

export interface Category {
  id: CategoryId;
  name: string;
  shortName: string;
  icon: string;
  description: string;
  image: string;
  color: string;
}

export const CATEGORIES: Category[] = [
  {
    id: "surf-kite",
    name: "Surf & Kite",
    shortName: "Surf",
    icon: "waves",
    description: "Clases de surf en Playa Caracol y kitesurf en Punta Chame con instructores certificados.",
    image: IMAGES.surfAction,
    color: "#0A2540",
  },
  {
    id: "acuaticas",
    name: "Acuáticas",
    shortName: "Islas",
    icon: "anchor",
    description: "Explora las islas Otoque y Boná, pesca artesanal y avistamiento de ballenas en el Pacífico.",
    image: IMAGES.islaOtoque,
    color: "#16537E",
  },
  {
    id: "premium",
    name: "Premium Adventures",
    shortName: "Premium",
    icon: "zap",
    description: "Jet ski, tubing, mulitas, 4-wheel y scooters en la playa. Adrenalina pura.",
    image: IMAGES.jetSki,
    color: "#D4A853",
  },
  {
    id: "botes-sthamas",
    name: "Bote Sthamas 39'",
    shortName: "Sthamas",
    icon: "ship",
    description: "Yate premium de 39 pies con A/C, cama, BBQ e internet. Hasta 12 pasajeros.",
    image: IMAGES.sunsetCruise,
    color: "#0A2540",
  },
  {
    id: "botes-rampage",
    name: "Bote Rampage 31'",
    shortName: "Rampage",
    icon: "sailboat",
    description: "Bote deportivo de 31 pies con cama, BBQ y todo incluido. Hasta 10 pasajeros.",
    image: IMAGES.fishingBoat,
    color: "#16537E",
  },
  {
    id: "eco-adventures",
    name: "Eco Adventures",
    shortName: "Eco",
    icon: "mountain",
    description: "Hiking, cascadas, rappel, tubing y el mágico Valle de Antón. Naturaleza pura.",
    image: IMAGES.cascadaFilipinas,
    color: "#2D5A4A",
  },
];

// Storytelling quotes per category (Default seeding)
export const QUOTES: Record<string, string> = {
  "surf-kite": "El viento y las olas no esperan. Tú tampoco deberías.",
  "acuaticas": "El océano tiene secretos que solo revela a quienes se atreven.",
  "premium": "Algunas experiencias no se describen. Se viven.",
  "botes-sthamas": "El horizonte es solo el comienzo de la aventura.",
  "botes-rampage": "Donde termina la costa, empieza lo extraordinario.",
  "eco-adventures": "La naturaleza panameña guarda tesoros que pocos conocen.",
};

// Gallery images per category (Default seeding)
export const GALLERY_IMAGES: Record<string, string[]> = {
  "surf-kite": [IMAGES.surfAction, IMAGES.kitesurfChame, IMAGES.beachAerial, IMAGES.caracolBeach],
  "acuaticas": [IMAGES.jetSki, IMAGES.islaOtoque, IMAGES.beachAerial, IMAGES.sunsetCruise],
  "premium": [IMAGES.whaleWatching, IMAGES.fishingSport, IMAGES.sunsetCruise, IMAGES.islaBonaCoast],
  "botes-sthamas": [IMAGES.sunsetCruise, IMAGES.islaOtoque, IMAGES.fishingSport, IMAGES.beachAerial],
  "botes-rampage": [IMAGES.fishingSport, IMAGES.sunsetCruise, IMAGES.islaBonaCoast, IMAGES.beachAerial],
  "eco-adventures": [IMAGES.cascadaFilipinas, IMAGES.cerroChame, IMAGES.valleAntonWaterfall, IMAGES.beachAerial],
};

// ============================================================
// TOUR INTERFACE
// ============================================================
export interface Tour {
  id: string;
  name: string;
  category: CategoryId;
  price: number;
  priceType: "per-person" | "per-group" | "per-vehicle";
  duration: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  maxPax: number;
  minPax?: number;
  available: string;
  commission: string;
  image: string;
  gallery: string[];
  location: string;
  meetingPoint: string;
  shortDescription: string;
  description: string;
  includes: string[];
  notIncludes: string[];
  whatToBring: string[];
  requirements?: string[];
  highlights: string[];
  schedule?: string;
  faq: { q: string; a: string }[];
}

// ============================================================
// SURF & KITE (8 tours)
// ============================================================
export const SURF_KITE_TOURS: Tour[] = [
  {
    id: "surf-101",
    name: "Surf 101",
    category: "surf-kite",
    price: 55,
    priceType: "per-person",
    duration: "1 hora",
    difficulty: 1,
    maxPax: 6,
    available: "Todo el año",
    commission: "20%",
    image: IMAGES.surfLesson,
    gallery: [IMAGES.surfLesson, IMAGES.surfGroup, IMAGES.surfSchool, IMAGES.chameWaves],
    location: "Mahana Tours, Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Tu primera ola te espera. Clase introductoria de surf para principiantes absolutos.",
    description: "No importa si nunca has tocado una tabla. En 60 minutos, nuestros instructores certificados te llevan desde la arena hasta tu primera ola. Playa Caracol tiene las condiciones perfectas para aprender: olas suaves, fondo de arena (sin piedras), y agua cálida todo el año. Incluye todo el equipo y un instructor que no te suelta hasta que te pares.",
    includes: ["Instructor certificado ISA", "Tabla de surf", "Rashguard", "Seguro de actividad", "Fotos de la sesión"],
    notIncludes: ["Transporte", "Alimentación", "Propinas"],
    whatToBring: ["Traje de baño", "Bloqueador solar reef-safe", "Toalla", "Ganas de mojarte"],
    highlights: ["Olas sin piedras", "Instructores certificados ISA", "Playa privada", "Fotos incluidas"],
    faq: [
      { q: "¿Necesito experiencia previa?", a: "No, esta clase es para principiantes absolutos. Empezamos desde cero." },
      { q: "¿Qué edad mínima?", a: "Desde 6 años con autorización de un adulto." },
      { q: "¿Qué pasa si no me paro?", a: "El 95% de nuestros alumnos se paran en la primera clase. Si no, te invitamos a repetir." },
    ],
  },
  {
    id: "surf-foundation",
    name: "Surf Foundation",
    category: "surf-kite",
    price: 300,
    priceType: "per-person",
    duration: "5 clases (2 meses)",
    difficulty: 2,
    maxPax: 6,
    available: "Todo el año",
    commission: "20%",
    image: IMAGES.surfGroup,
    gallery: [IMAGES.surfGroup, IMAGES.surfAction, IMAGES.surfSchool, IMAGES.beachAerial],
    location: "Mahana Tours, Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "5 clases para construir una base sólida. De principiante a surfista independiente.",
    description: "El paquete Foundation es para quienes quieren ir en serio. En 5 sesiones distribuidas en 2 meses, pasas de principiante a surfista independiente. Cada clase construye sobre la anterior: postura, remada, lectura de olas, pop-up y primeras maniobras. Al final, surfeas solo con confianza.",
    includes: ["5 clases de 1 hora", "Instructor certificado ISA", "Tabla y equipo completo", "Video análisis (última clase)", "Certificado Mahana Tours"],
    notIncludes: ["Transporte", "Alimentación"],
    whatToBring: ["Traje de baño", "Bloqueador solar", "Hidratación", "Toalla"],
    highlights: ["Progresión garantizada", "Video análisis incluido", "Certificado Mahana Tours", "Horarios flexibles"],
    faq: [
      { q: "¿Puedo elegir los horarios?", a: "Sí, coordinamos las 5 sesiones según tu disponibilidad." },
      { q: "¿Las clases son privadas?", a: "Máximo 6 personas por grupo para atención personalizada." },
    ],
  },
  {
    id: "surf-accelerator",
    name: "Surf Accelerator",
    category: "surf-kite",
    price: 685,
    priceType: "per-person",
    duration: "10 clases (4 meses)",
    difficulty: 3,
    maxPax: 6,
    available: "Todo el año",
    commission: "20%",
    image: IMAGES.surfAction,
    gallery: [IMAGES.surfAction, IMAGES.surfSunset, IMAGES.surfGroup, IMAGES.chameWaves],
    location: "Mahana Tours, Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "10 clases intensivas. De principiante a surfista con estilo propio.",
    description: "El programa de Mahana Tours más completo. 10 sesiones en 4 meses que te llevan desde cero hasta surfear con confianza y estilo propio. Incluye video análisis, teoría de olas, y las primeras maniobras. Al graduarte, eres parte de la comunidad Mahana Tours.",
    includes: ["10 clases de 1 hora", "Instructor certificado ISA", "Equipo completo", "3 sesiones de video análisis", "Certificado Mahana Tours Accelerator", "Camiseta Mahana Tours"],
    notIncludes: ["Transporte", "Alimentación"],
    whatToBring: ["Traje de baño", "Bloqueador solar", "Hidratación", "Toalla"],
    highlights: ["Programa más completo", "3 video análisis", "Comunidad Mahana Tours", "Camiseta incluida"],
    faq: [
      { q: "¿Puedo pausar el programa?", a: "Sí, tienes hasta 6 meses para completar las 10 sesiones." },
      { q: "¿Qué nivel alcanzo?", a: "Al terminar, surfeas olas de 2-4 pies de forma independiente con maniobras básicas." },
    ],
  },
  {
    id: "surf-camp-kids",
    name: "Surf Camp Kids",
    category: "surf-kite",
    price: 300,
    priceType: "per-person",
    duration: "1 día",
    difficulty: 1,
    maxPax: 12,
    available: "Temporada escolar",
    commission: "20%",
    image: IMAGES.surfSchool,
    gallery: [IMAGES.surfSchool, IMAGES.surfGroup, IMAGES.beachAerial],
    location: "Mahana Tours, Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Un día de surf, playa y diversión para los más pequeños.",
    description: "Un día completo de aventura para niños. Surf, juegos en la playa, almuerzo incluido y mucha diversión. Instructores especializados en enseñanza infantil con ratio 1:3 para máxima seguridad.",
    includes: ["Clases de surf", "Equipo completo", "Almuerzo", "Snacks y agua", "Fotos", "Seguro"],
    notIncludes: ["Transporte"],
    whatToBring: ["Traje de baño", "Bloqueador solar", "Muda de ropa", "Toalla"],
    highlights: ["Ratio 1:3 instructor/niño", "Almuerzo incluido", "Ambiente seguro", "Fotos incluidas"],
    faq: [
      { q: "¿Qué edades?", a: "De 6 a 14 años." },
      { q: "¿Los padres pueden quedarse?", a: "Sí, hay área de observación con sombra y bebidas disponibles." },
    ],
  },
  {
    id: "surf-camp-adultos",
    name: "Surf Camp Adultos",
    category: "surf-kite",
    price: 300,
    priceType: "per-person",
    duration: "1 día",
    difficulty: 2,
    maxPax: 12,
    available: "Temporada",
    commission: "20%",
    image: IMAGES.surfSunset,
    gallery: [IMAGES.surfSunset, IMAGES.surfAction, IMAGES.surfGroup, IMAGES.ventoClub],
    location: "Mahana Tours, Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Un día completo de surf, comunidad y buena vibra en Playa Caracol.",
    description: "Surf camp de un día para adultos. Sesión matutina de surf, almuerzo en Vento Beach Club, sesión de tarde, y atardecer en la playa. La combinación perfecta de deporte, gastronomía y comunidad.",
    includes: ["2 sesiones de surf", "Equipo completo", "Almuerzo en Vento", "Instructor certificado", "Fotos y video"],
    notIncludes: ["Transporte", "Bebidas alcohólicas"],
    whatToBring: ["Traje de baño", "Bloqueador solar", "Toalla", "Buena actitud"],
    highlights: ["Almuerzo en Vento Beach Club", "2 sesiones de surf", "Comunidad adulta", "Fotos y video"],
    faq: [
      { q: "¿Necesito experiencia?", a: "No, hay grupos por nivel." },
      { q: "¿Hay límite de edad?", a: "No, hemos tenido alumnos de 18 a 65 años." },
    ],
  },
  {
    id: "kite-surf-clase",
    name: "Kite Surf Clase",
    category: "surf-kite",
    price: 90,
    priceType: "per-person",
    duration: "1 hora",
    difficulty: 3,
    maxPax: 4,
    available: "Nov - Mar",
    commission: "5%",
    image: IMAGES.kitesurfChame,
    gallery: [IMAGES.kitesurfChame, IMAGES.kitesurfAerial, IMAGES.kitesurfAction],
    location: "Punta Chame",
    meetingPoint: "Punta Chame",
    shortDescription: "Vuela sobre el agua. Clase introductoria de kitesurf en Punta Chame.",
    description: "Punta Chame es uno de los mejores spots de kitesurf en Centroamérica. Vientos constantes de noviembre a marzo, aguas planas y kilómetros de playa. Tu clase incluye teoría en tierra, control del kite, y primeros metros sobre el agua.",
    includes: ["Instructor certificado IKO", "Equipo completo de kite", "Seguro de actividad"],
    notIncludes: ["Transporte a Punta Chame", "Alimentación"],
    whatToBring: ["Traje de baño", "Bloqueador solar", "Lentes con correa", "Agua"],
    requirements: ["Saber nadar", "Mayores de 12 años"],
    highlights: ["Vientos constantes", "Aguas planas", "Instructor IKO", "Spot clase mundial"],
    faq: [
      { q: "¿Por qué solo Nov-Mar?", a: "Es la temporada de vientos alisios en Punta Chame, con condiciones ideales." },
      { q: "¿Incluye transporte?", a: "No, pero podemos coordinar transporte desde Playa Caracol por un costo adicional." },
    ],
  },
  {
    id: "kite-surf-pack",
    name: "Kite Surf Pack IKO",
    category: "surf-kite",
    price: 630,
    priceType: "per-person",
    duration: "8 horas",
    difficulty: 3,
    maxPax: 4,
    available: "Nov - Mar",
    commission: "5%",
    image: IMAGES.kitesurfAction,
    gallery: [IMAGES.kitesurfAction, IMAGES.kitesurfChame, IMAGES.kitesurfAerial],
    location: "Punta Chame",
    meetingPoint: "Punta Chame",
    shortDescription: "Curso completo de kitesurf con certificación IKO internacional.",
    description: "El paquete completo para convertirte en kitesurfista certificado. 8 horas de instrucción divididas en sesiones, cubriendo desde teoría hasta navegación independiente. Al completar, recibes tu certificación IKO reconocida mundialmente.",
    includes: ["8 horas de instrucción", "Certificación IKO", "Equipo completo", "Seguro de actividad"],
    notIncludes: ["Transporte a Punta Chame", "Alimentación", "Alojamiento"],
    whatToBring: ["Traje de baño", "Bloqueador solar", "Hidratación", "Snacks"],
    requirements: ["Saber nadar bien", "Mayores de 14 años", "Condición física moderada"],
    highlights: ["Certificación IKO internacional", "8 horas de instrucción", "Navegación independiente", "Spot clase mundial"],
    faq: [
      { q: "¿En cuántos días se completa?", a: "Generalmente 2-3 días dependiendo de las condiciones de viento." },
      { q: "¿La certificación es válida mundialmente?", a: "Sí, IKO es la organización internacional de kitesurf más reconocida." },
    ],
  },
  {
    id: "wing-foil",
    name: "Wing Foil",
    category: "surf-kite",
    price: 120,
    priceType: "per-person",
    duration: "1 hora",
    difficulty: 4,
    maxPax: 3,
    available: "Nov - Mar",
    commission: "5%",
    image: IMAGES.kitesurfAerial,
    gallery: [IMAGES.kitesurfAerial, IMAGES.kitesurfChame],
    location: "Punta Chame",
    meetingPoint: "Punta Chame",
    shortDescription: "El deporte acuático del momento. Vuela sobre el agua con un wing y un foil.",
    description: "Wing foil es la última revolución en deportes acuáticos. Combina un ala inflable con una tabla de hydrofoil para literalmente volar sobre el agua. Clase introductoria en las aguas planas de Punta Chame.",
    includes: ["Instructor especializado", "Equipo completo (wing + foil board)", "Seguro"],
    notIncludes: ["Transporte", "Alimentación"],
    whatToBring: ["Traje de baño", "Bloqueador solar", "Buena condición física"],
    requirements: ["Experiencia previa en deportes acuáticos recomendada", "Mayores de 16 años"],
    highlights: ["Deporte de vanguardia", "Aguas planas ideales", "Equipo premium", "Experiencia única"],
    faq: [
      { q: "¿Necesito saber kitesurf?", a: "No es obligatorio, pero experiencia en deportes acuáticos ayuda mucho." },
    ],
  },
];

// ============================================================
// ACUÁTICAS (5 tours)
// ============================================================
export const ACUATICAS_TOURS: Tour[] = [
  {
    id: "pesca-otoque-bona",
    name: "Pesca Otoque y Boná",
    category: "acuaticas",
    price: 330,
    priceType: "per-group",
    duration: "4 horas",
    difficulty: 2,
    maxPax: 5,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.fishingCatch,
    gallery: [IMAGES.fishingCatch, IMAGES.fishingSport, IMAGES.fishingBoat, IMAGES.islaBonaCoast],
    location: "Islas Otoque y Boná",
    meetingPoint: "Punta Chame",
    shortDescription: "Pesca artesanal en las islas del Pacífico. Meros, pargos y la emoción de la captura.",
    description: "Sal a pescar como los locales. Navegamos hasta las islas Otoque y Boná donde las aguas son ricas en meros, pargos, corvinas y más. 4 horas de pesca con equipo incluido, cooler con bebidas, y un guía local que conoce cada rincón de estas aguas.",
    includes: ["Bote con toldo", "Equipo de pesca", "Cooler con agua y sodas", "Guía local", "Carnada"],
    notIncludes: ["Transporte a Punta Chame", "Alimentación", "Bebidas alcohólicas", "Licencia de pesca (incluida)"],
    whatToBring: ["Bloqueador solar", "Gorra", "Lentes de sol", "Ropa cómoda", "Cámara waterproof"],
    highlights: ["Islas del Pacífico", "Guía local experto", "Equipo incluido", "Cooler con bebidas"],
    faq: [
      { q: "¿Qué peces se capturan?", a: "Meros, pargos, corvinas, jureles y ocasionalmente atún." },
      { q: "¿Se puede comer lo que se pesca?", a: "Sí, podemos coordinar que lo preparen en un restaurante local." },
      { q: "¿Es apto para niños?", a: "Sí, desde 6 años con adulto responsable." },
    ],
  },
  {
    id: "isla-otoque-bona",
    name: "Isla Otoque y Boná",
    category: "acuaticas",
    price: 300,
    priceType: "per-group",
    duration: "4 horas",
    difficulty: 1,
    maxPax: 5,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.islaOtoque,
    gallery: [IMAGES.islaOtoque, IMAGES.islaBonaCoast, IMAGES.beachAerial],
    location: "Islas Otoque y Boná",
    meetingPoint: "Punta Chame",
    shortDescription: "Explora islas vírgenes del Pacífico. Snorkel, playa privada y naturaleza intacta.",
    description: "Un viaje a las islas que el tiempo olvidó. Otoque y Boná son dos joyas del Pacífico panameño con playas vírgenes, aguas cristalinas y una tranquilidad que no encontrarás en ningún otro lugar. Snorkel, caminata por la isla, y tiempo libre en playas donde eres el único visitante.",
    includes: ["Bote con toldo", "Equipo de snorkel", "Cooler con agua y sodas", "Guía local"],
    notIncludes: ["Transporte a Punta Chame", "Alimentación", "Bebidas alcohólicas"],
    whatToBring: ["Traje de baño", "Bloqueador solar reef-safe", "Toalla", "Cámara", "Snacks"],
    highlights: ["Playas vírgenes", "Snorkel en aguas cristalinas", "Islas sin turismo masivo", "Naturaleza intacta"],
    faq: [
      { q: "¿Cuánto tarda el viaje en bote?", a: "Aproximadamente 30-45 minutos desde Punta Chame." },
      { q: "¿Hay señal de celular?", a: "Muy limitada. Es parte del encanto de desconectar." },
    ],
  },
  {
    id: "day-pass-taborcillo",
    name: "Day Pass Taborcillo",
    category: "acuaticas",
    price: 150,
    priceType: "per-person",
    duration: "3 horas",
    difficulty: 1,
    maxPax: 5,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.islaBonaCoast,
    gallery: [IMAGES.islaBonaCoast, IMAGES.islaOtoque, IMAGES.beachAerial],
    location: "Isla Taborcillo",
    meetingPoint: "Punta Chame",
    shortDescription: "Un día en una isla privada del Pacífico. Playa, snorkel y relax total.",
    description: "Isla Taborcillo es una isla privada con infraestructura para pasar un día perfecto. Playa exclusiva, aguas tranquilas para snorkel, y la sensación de estar en tu propia isla del Pacífico.",
    includes: ["Bote ida y vuelta", "Acceso a la isla", "Cooler con agua y sodas", "Guía"],
    notIncludes: ["Alimentación en la isla", "Equipo de snorkel (disponible para alquilar)", "Transporte a Punta Chame"],
    whatToBring: ["Traje de baño", "Bloqueador solar", "Toalla", "Efectivo para extras"],
    highlights: ["Isla privada", "Aguas tranquilas", "Exclusividad", "Infraestructura en la isla"],
    faq: [
      { q: "¿Hay comida en la isla?", a: "Hay opciones básicas disponibles, pero recomendamos llevar snacks." },
    ],
  },
  {
    id: "manglares-taborcillo",
    name: "Manglares + Taborcillo",
    category: "acuaticas",
    price: 270,
    priceType: "per-group",
    duration: "3 horas",
    difficulty: 1,
    maxPax: 5,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.beachAerial,
    gallery: [IMAGES.beachAerial, IMAGES.islaBonaCoast, IMAGES.islaOtoque],
    location: "Manglares de Chame + Isla Taborcillo",
    meetingPoint: "Punta Chame",
    shortDescription: "Recorre los manglares en bote y termina en una isla privada. Naturaleza y relax.",
    description: "Una experiencia doble: primero navegamos por los manglares de Chame, un ecosistema único lleno de aves, cangrejos y vida marina. Luego cruzamos a Isla Taborcillo para relajarte en la playa. Lo mejor de dos mundos.",
    includes: ["Bote con toldo", "Recorrido por manglares", "Acceso a Taborcillo", "Cooler con agua y sodas", "Guía naturalista"],
    notIncludes: ["Transporte a Punta Chame", "Alimentación"],
    whatToBring: ["Binoculares (opcional)", "Cámara", "Bloqueador solar", "Ropa cómoda"],
    highlights: ["Ecosistema de manglares", "Avistamiento de aves", "Isla privada", "Guía naturalista"],
    faq: [
      { q: "¿Qué animales se ven en los manglares?", a: "Pelícanos, garzas, fragatas, cangrejos, y ocasionalmente delfines." },
    ],
  },
  {
    id: "avistamiento-ballenas",
    name: "Avistamiento de Ballenas",
    category: "acuaticas",
    price: 300,
    priceType: "per-group",
    duration: "2 horas",
    difficulty: 1,
    maxPax: 5,
    available: "Jul - Oct",
    commission: "10%",
    image: IMAGES.whaleBreach,
    gallery: [IMAGES.whaleBreach, IMAGES.whaleWatching, IMAGES.islaBonaCoast],
    location: "Aguas del Pacífico, Punta Chame",
    meetingPoint: "Punta Chame",
    shortDescription: "Ballenas jorobadas en el Pacífico panameño. Un espectáculo que cambia tu vida.",
    description: "Cada año, de julio a octubre, las ballenas jorobadas migran desde la Antártida hasta las cálidas aguas del Pacífico panameño para dar a luz y criar a sus ballenatos. Desde Punta Chame, navegamos hasta encontrarlas. Ver una ballena de 40 toneladas saltar fuera del agua es algo que no se olvida jamás.",
    includes: ["Bote con toldo", "Guía especializado en cetáceos", "Cooler con agua y sodas", "Binoculares"],
    notIncludes: ["Transporte a Punta Chame", "Alimentación"],
    whatToBring: ["Cámara con zoom", "Bloqueador solar", "Gorra", "Medicamento para mareo (si aplica)"],
    highlights: ["Ballenas jorobadas", "Temporada Jul-Oct", "Guía especializado", "Experiencia única"],
    schedule: "Salida 8:00am, regreso ~10:00am",
    faq: [
      { q: "¿Se garantiza ver ballenas?", a: "No podemos garantizarlo al 100%, pero la tasa de avistamiento en temporada es superior al 90%." },
      { q: "¿Es seguro?", a: "Sí, mantenemos distancia regulada y el bote tiene todas las medidas de seguridad." },
      { q: "¿Niños pueden ir?", a: "Sí, desde 4 años. Es una experiencia educativa increíble para ellos." },
    ],
  },
];

// ============================================================
// PREMIUM ADVENTURES (12 tours)
// ============================================================
export const PREMIUM_TOURS: Tour[] = [
  {
    id: "jet-ski-1h",
    name: "Jet Ski — 1 Hora",
    category: "premium",
    price: 140,
    priceType: "per-person",
    duration: "1 hora",
    difficulty: 2,
    maxPax: 2,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.jetSki,
    gallery: [IMAGES.jetSki, IMAGES.beachAerial, IMAGES.caracolBeach],
    location: "Mahana Tours, Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Adrenalina sobre el agua. Recorre la costa de Playa Caracol en jet ski.",
    description: "Una hora de libertad total sobre el agua. Recorre la costa de Playa Caracol, siente la velocidad y disfruta las vistas desde el mar. Jet skis Yamaha de última generación con toda la seguridad.",
    includes: ["Jet ski Yamaha", "Chaleco salvavidas", "Briefing de seguridad", "Seguro"],
    notIncludes: ["Gasolina adicional (incluida en el precio)", "Fotos"],
    whatToBring: ["Traje de baño", "Bloqueador solar waterproof", "Lentes con correa"],
    requirements: ["Mayores de 18 años", "Saber nadar"],
    highlights: ["Jet ski Yamaha", "Costa de Playa Caracol", "Vistas panorámicas", "Adrenalina pura"],
    faq: [
      { q: "¿Puedo llevar acompañante?", a: "Sí, cada jet ski admite 2 personas." },
      { q: "¿Necesito licencia?", a: "No, se proporciona briefing de seguridad antes de salir." },
    ],
  },
  {
    id: "jet-ski-30",
    name: "Jet Ski — 30 Min",
    category: "premium",
    price: 75,
    priceType: "per-person",
    duration: "30 minutos",
    difficulty: 2,
    maxPax: 2,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.jetSki,
    gallery: [IMAGES.jetSki, IMAGES.beachAerial],
    location: "Mahana Tours, Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Media hora de jet ski para probar la experiencia sin compromiso.",
    description: "La opción perfecta para quienes quieren probar el jet ski sin comprometerse a una hora completa. 30 minutos de adrenalina pura en la costa de Playa Caracol.",
    includes: ["Jet ski Yamaha", "Chaleco salvavidas", "Briefing de seguridad", "Seguro"],
    notIncludes: ["Fotos"],
    whatToBring: ["Traje de baño", "Bloqueador solar waterproof"],
    requirements: ["Mayores de 18 años"],
    highlights: ["Opción rápida", "Ideal para probar", "Mismo equipo premium"],
    faq: [{ q: "¿Puedo extender a 1 hora?", a: "Sí, sujeto a disponibilidad, pagas la diferencia." }],
  },
  {
    id: "jet-ski-15",
    name: "Jet Ski — 15 Min",
    category: "premium",
    price: 45,
    priceType: "per-person",
    duration: "15 minutos",
    difficulty: 2,
    maxPax: 2,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.jetSki,
    gallery: [IMAGES.jetSki],
    location: "Mahana Tours, Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Un shot de adrenalina. 15 minutos de jet ski para sentir la velocidad.",
    description: "El shot de adrenalina perfecto. 15 minutos de jet ski para quienes quieren una experiencia rápida pero intensa.",
    includes: ["Jet ski Yamaha", "Chaleco salvavidas", "Briefing", "Seguro"],
    notIncludes: ["Fotos"],
    whatToBring: ["Traje de baño"],
    requirements: ["Mayores de 18 años"],
    highlights: ["Experiencia express", "Precio accesible", "Adrenalina inmediata"],
    faq: [],
  },
  {
    id: "tubing-1h",
    name: "Tubing Inflable — 1 Hora",
    category: "premium",
    price: 140,
    priceType: "per-group",
    duration: "1 hora",
    difficulty: 2,
    maxPax: 3,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.tubingGroup,
    gallery: [IMAGES.tubingGroup, IMAGES.beachAerial],
    location: "Mahana Tours, Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "3 personas, 1 inflable, velocidad y risas garantizadas.",
    description: "El tubing inflable es diversión garantizada. Hasta 3 personas se montan en un inflable remolcado por una lancha a toda velocidad. Giros, saltos y muchas risas. Ideal para familias y grupos de amigos.",
    includes: ["Inflable para 3 personas", "Lancha de remolque", "Chalecos salvavidas", "Seguro"],
    notIncludes: ["Fotos", "Video"],
    whatToBring: ["Traje de baño", "Ganas de gritar"],
    requirements: ["1 adulto responsable por grupo"],
    highlights: ["Hasta 3 personas", "Diversión familiar", "Risas garantizadas"],
    faq: [{ q: "¿Es seguro para niños?", a: "Sí, desde 6 años con adulto responsable en el inflable." }],
  },
  {
    id: "tubing-30",
    name: "Tubing Inflable — 30 Min",
    category: "premium",
    price: 75,
    priceType: "per-group",
    duration: "30 minutos",
    difficulty: 2,
    maxPax: 3,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.tubingGroup,
    gallery: [IMAGES.tubingGroup],
    location: "Mahana Tours, Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Media hora de tubing para probar la experiencia.",
    description: "30 minutos de tubing inflable. Suficiente para sentir la adrenalina y las risas sin agotarse.",
    includes: ["Inflable para 3", "Lancha", "Chalecos", "Seguro"],
    notIncludes: ["Fotos"],
    whatToBring: ["Traje de baño"],
    requirements: ["1 adulto responsable"],
    highlights: ["Opción corta", "Ideal para probar"],
    faq: [],
  },
  {
    id: "tubing-15",
    name: "Tubing Inflable — 15 Min",
    category: "premium",
    price: 45,
    priceType: "per-group",
    duration: "15 minutos",
    difficulty: 2,
    maxPax: 3,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.tubingGroup,
    gallery: [IMAGES.tubingGroup],
    location: "Mahana Tours, Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "15 minutos de tubing express. Rápido, divertido, memorable.",
    description: "La versión express del tubing. 15 minutos de pura diversión sobre el agua.",
    includes: ["Inflable para 3", "Lancha", "Chalecos", "Seguro"],
    notIncludes: ["Fotos"],
    whatToBring: ["Traje de baño"],
    requirements: ["1 adulto responsable"],
    highlights: ["Express", "Precio accesible"],
    faq: [],
  },
  {
    id: "mulita-30",
    name: "Beach Buggy (Mulita) — 30 Min",
    category: "premium",
    price: 80,
    priceType: "per-vehicle",
    duration: "30 minutos",
    difficulty: 1,
    maxPax: 4,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.caracolBeach,
    gallery: [IMAGES.caracolBeach, IMAGES.beachAerial],
    location: "Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Recorre Playa Caracol en buggy. 4 personas, viento en la cara, playa infinita.",
    description: "Sube a una mulita (beach buggy) y recorre la costa de Playa Caracol. Hasta 4 personas por vehículo, ideal para familias. 30 minutos de paseo con vistas al mar y al Cerro Chame.",
    includes: ["Beach buggy", "Gasolina", "Briefing de manejo", "Seguro"],
    notIncludes: ["Fotos"],
    whatToBring: ["Licencia de conducir", "Bloqueador solar", "Lentes de sol"],
    requirements: ["Licencia de conducir vigente", "Mayor de edad"],
    highlights: ["Hasta 4 personas", "Vistas al Cerro Chame", "Diversión familiar"],
    faq: [{ q: "¿Necesito licencia?", a: "Sí, el conductor debe tener licencia de conducir vigente." }],
  },
  {
    id: "mulita-50",
    name: "Beach Buggy (Mulita) — 50 Min",
    category: "premium",
    price: 120,
    priceType: "per-vehicle",
    duration: "50 minutos",
    difficulty: 1,
    maxPax: 4,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.caracolBeach,
    gallery: [IMAGES.caracolBeach, IMAGES.beachAerial, IMAGES.cerroChame],
    location: "Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Recorrido extendido en buggy. Más playa, más vistas, más diversión.",
    description: "La versión extendida del paseo en mulita. 50 minutos para recorrer más de la costa, llegar hasta puntos panorámicos y disfrutar sin prisa.",
    includes: ["Beach buggy", "Gasolina", "Briefing", "Seguro"],
    notIncludes: ["Fotos"],
    whatToBring: ["Licencia de conducir", "Bloqueador solar"],
    requirements: ["Licencia de conducir", "Mayor de edad"],
    highlights: ["Recorrido extendido", "Puntos panorámicos", "Sin prisa"],
    faq: [],
  },
  {
    id: "mulita-3h",
    name: "Beach Buggy (Mulita) — 3 Horas",
    category: "premium",
    price: 325,
    priceType: "per-vehicle",
    duration: "3 horas",
    difficulty: 2,
    maxPax: 4,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.cerroChame,
    gallery: [IMAGES.cerroChame, IMAGES.caracolBeach, IMAGES.beachAerial],
    location: "Playa Caracol y alrededores",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Expedición completa en buggy. Recorre toda la costa y los alrededores de Chame.",
    description: "La experiencia completa en mulita. 3 horas para explorar toda la costa de Playa Caracol, los alrededores de Chame, y puntos que solo se alcanzan en vehículo todo terreno. Una mini-aventura sobre ruedas.",
    includes: ["Beach buggy", "Gasolina", "Briefing", "Seguro", "Mapa de ruta"],
    notIncludes: ["Alimentación", "Fotos"],
    whatToBring: ["Licencia de conducir", "Bloqueador solar", "Agua", "Snacks"],
    requirements: ["Licencia de conducir", "Mayor de edad"],
    highlights: ["Expedición completa", "Ruta panorámica", "3 horas de exploración"],
    faq: [{ q: "¿Puedo parar en el camino?", a: "Sí, puedes parar donde quieras dentro de la ruta permitida." }],
  },
  {
    id: "4wheel-30",
    name: "4 Wheel — 30 Min",
    category: "premium",
    price: 55,
    priceType: "per-person",
    duration: "30 minutos",
    difficulty: 2,
    maxPax: 1,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.beachAerial,
    gallery: [IMAGES.beachAerial, IMAGES.caracolBeach],
    location: "Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Cuatrimoto por la playa. Arena, velocidad y vistas al Pacífico.",
    description: "Recorre la playa en cuatrimoto. 30 minutos de arena, velocidad controlada y vistas al Pacífico. Una experiencia que combina adrenalina con paisajes.",
    includes: ["Cuatrimoto", "Casco", "Briefing de seguridad", "Seguro"],
    notIncludes: ["Fotos"],
    whatToBring: ["Ropa cómoda", "Zapatos cerrados", "Bloqueador solar"],
    requirements: ["Mayor de edad"],
    highlights: ["Cuatrimoto en la playa", "Vistas al Pacífico", "Fácil de manejar"],
    faq: [],
  },
  {
    id: "4wheel-50",
    name: "4 Wheel — 50 Min",
    category: "premium",
    price: 80,
    priceType: "per-person",
    duration: "50 minutos",
    difficulty: 2,
    maxPax: 1,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.beachAerial,
    gallery: [IMAGES.beachAerial, IMAGES.caracolBeach, IMAGES.cerroChame],
    location: "Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Recorrido extendido en cuatrimoto. Más playa, más adrenalina.",
    description: "50 minutos en cuatrimoto para recorrer más de la costa y llegar a puntos que no alcanzas en 30 minutos.",
    includes: ["Cuatrimoto", "Casco", "Briefing", "Seguro"],
    notIncludes: ["Fotos"],
    whatToBring: ["Ropa cómoda", "Zapatos cerrados"],
    requirements: ["Mayor de edad"],
    highlights: ["Recorrido extendido", "Más puntos panorámicos"],
    faq: [],
  },
  {
    id: "scooter",
    name: "Scooter Eléctrico",
    category: "premium",
    price: 18,
    priceType: "per-person",
    duration: "1 hora",
    difficulty: 1,
    maxPax: 1,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.caracolAerial2,
    gallery: [IMAGES.caracolAerial2, IMAGES.caracolBeach],
    location: "Playa Caracol",
    meetingPoint: "Mahana Tours, Playa Caracol",
    shortDescription: "Recorre Playa Caracol en scooter eléctrico. Fácil, divertido, para todos.",
    description: "La forma más fácil y divertida de recorrer Playa Caracol. Scooters eléctricos para toda la familia. Sin ruido, sin emisiones, solo diversión.",
    includes: ["Scooter eléctrico", "Casco", "Briefing", "Seguro"],
    notIncludes: [],
    whatToBring: ["ID o pasaporte", "Zapatos cómodos"],
    requirements: ["Adulto responsable para menores"],
    highlights: ["Ecológico", "Fácil de usar", "Para toda la familia", "Precio accesible"],
    faq: [{ q: "¿Desde qué edad?", a: "Desde 12 años con adulto responsable, desde 16 años solo." }],
  },
];

// ============================================================
// BOTES STHAMAS 39' (6 tours)
// ============================================================
export const STHAMAS_TOURS: Tour[] = [
  {
    id: "sthamas-sunset",
    name: "Caracol Sunset Cruise",
    category: "botes-sthamas",
    price: 863,
    priceType: "per-group",
    duration: "3 horas",
    difficulty: 1,
    maxPax: 12,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.sunsetCruise,
    gallery: [IMAGES.sunsetCruise, IMAGES.beachAerial, IMAGES.islaBonaCoast],
    location: "Costa de Playa Caracol",
    meetingPoint: "Vista Mar, Playa Caracol",
    shortDescription: "Atardecer en yate privado. Cócteles, música y el Pacífico pintado de oro.",
    description: "El atardecer más espectacular de Panamá visto desde un yate de 39 pies. Navegamos la costa de Playa Caracol mientras el sol pinta el cielo de oro y coral. Incluye aire acondicionado, cama, BBQ, internet y todo lo que necesitas para una experiencia premium.",
    includes: ["Yate Sthamas 39'", "Capitán y tripulación", "Aire acondicionado", "BBQ a bordo", "Agua, hielo", "Internet WiFi", "Equipo de sonido"],
    notIncludes: ["Bebidas alcohólicas (puedes traer las tuyas)", "Comida (BBQ disponible para tu uso)"],
    whatToBring: ["Bebidas de tu preferencia", "Comida para BBQ", "Cámara", "Ropa cómoda"],
    highlights: ["Yate premium 39 pies", "Hasta 12 personas", "A/C y WiFi", "BBQ a bordo", "Atardecer del Pacífico"],
    schedule: "Salida 4:00pm, regreso 7:00pm",
    faq: [
      { q: "¿Puedo llevar mi propia bebida?", a: "Sí, el yate incluye hielo y cooler. Trae lo que quieras." },
      { q: "¿Hay música?", a: "Sí, el yate tiene equipo de sonido. Puedes conectar tu playlist." },
      { q: "¿Es privado?", a: "Sí, el precio es por el yate completo, no por persona." },
    ],
  },
  {
    id: "sthamas-party",
    name: "Sail Away Party",
    category: "botes-sthamas",
    price: 1123,
    priceType: "per-group",
    duration: "3 horas",
    difficulty: 1,
    maxPax: 12,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.sunsetCruise,
    gallery: [IMAGES.sunsetCruise, IMAGES.beachAerial],
    location: "Costa de Playa Caracol",
    meetingPoint: "Vista Mar, Playa Caracol",
    shortDescription: "Fiesta en yate privado. Tu evento flotante en el Pacífico.",
    description: "Cumpleaños, despedida de soltero/a, celebración corporativa o simplemente porque sí. El Sail Away Party es tu evento privado en un yate de 39 pies con todo incluido. 3 horas de fiesta sobre el Pacífico.",
    includes: ["Yate Sthamas 39'", "Capitán y tripulación", "A/C", "BBQ", "Agua, hielo", "WiFi", "Sonido premium", "Decoración básica"],
    notIncludes: ["Bebidas alcohólicas", "Comida", "Decoración temática especial"],
    whatToBring: ["Bebidas", "Comida para BBQ", "Decoración extra si deseas"],
    highlights: ["Evento privado flotante", "Hasta 12 invitados", "Sonido premium", "BBQ a bordo"],
    schedule: "Horario flexible, coordinar al reservar",
    faq: [
      { q: "¿Puedo decorar el yate?", a: "Sí, incluimos decoración básica y puedes agregar la tuya." },
      { q: "¿Hay DJ disponible?", a: "Podemos coordinar un DJ por un costo adicional." },
    ],
  },
  {
    id: "sthamas-daypass",
    name: "Day Pass Boná y Otoque",
    category: "botes-sthamas",
    price: 2163,
    priceType: "per-group",
    duration: "8 horas",
    difficulty: 1,
    maxPax: 12,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.islaOtoque,
    gallery: [IMAGES.islaOtoque, IMAGES.islaBonaCoast, IMAGES.sunsetCruise],
    location: "Islas Boná y Otoque",
    meetingPoint: "Vista Mar, Playa Caracol",
    shortDescription: "Un día completo en yate explorando las islas del Pacífico. La experiencia definitiva.",
    description: "8 horas en yate premium explorando las islas Boná y Otoque. Snorkel en aguas cristalinas, playa virgen, BBQ a bordo, y la libertad de un día completo en el Pacífico. La experiencia náutica definitiva.",
    includes: ["Yate Sthamas 39'", "Capitán y tripulación", "A/C", "BBQ", "Agua, hielo", "WiFi", "Equipo de snorkel"],
    notIncludes: ["Bebidas alcohólicas", "Comida (BBQ disponible)"],
    whatToBring: ["Comida para BBQ", "Bebidas", "Bloqueador solar", "Toalla", "Cámara"],
    highlights: ["8 horas de navegación", "Islas vírgenes", "Snorkel incluido", "BBQ a bordo"],
    schedule: "Salida 8:00am, regreso 4:00-6:00pm",
    faq: [
      { q: "¿Cuánto tarda llegar a las islas?", a: "Aproximadamente 45 minutos a 1 hora." },
    ],
  },
  {
    id: "sthamas-fun-fishing",
    name: "Fun Fishing",
    category: "botes-sthamas",
    price: 2163,
    priceType: "per-group",
    duration: "6 horas",
    difficulty: 2,
    maxPax: 12,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.fishingCatch,
    gallery: [IMAGES.fishingCatch, IMAGES.fishingSport, IMAGES.fishingBoat],
    location: "Aguas del Pacífico",
    meetingPoint: "Vista Mar, Playa Caracol",
    shortDescription: "Pesca deportiva en yate premium. 6 horas de acción en el Pacífico.",
    description: "Pesca deportiva en un yate de 39 pies con todo el equipo profesional. 6 horas en las aguas más ricas del Pacífico panameño. Meros, pargos, atún, dorado y más. Para pescadores serios y novatos por igual.",
    includes: ["Yate Sthamas 39'", "Equipo de pesca profesional", "Carnada", "Capitán y tripulación", "A/C", "Agua, hielo"],
    notIncludes: ["Bebidas alcohólicas", "Comida"],
    whatToBring: ["Bloqueador solar", "Gorra", "Comida", "Bebidas"],
    highlights: ["Equipo profesional", "6 horas de pesca", "Yate con A/C", "Aguas ricas del Pacífico"],
    schedule: "Salida 7:00am, regreso 1:00pm",
    faq: [
      { q: "¿Qué se pesca?", a: "Meros, pargos, corvinas, atún, dorado, wahoo y más según temporada." },
    ],
  },
  {
    id: "sthamas-pro-fishing",
    name: "Pro Fishing",
    category: "botes-sthamas",
    price: 3073,
    priceType: "per-group",
    duration: "10 horas",
    difficulty: 3,
    maxPax: 12,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.fishingSport,
    gallery: [IMAGES.fishingSport, IMAGES.fishingCatch, IMAGES.fishingBoat],
    location: "Aguas profundas del Pacífico",
    meetingPoint: "Vista Mar, Playa Caracol",
    shortDescription: "Pesca de altura en yate premium. 10 horas para los que van en serio.",
    description: "La experiencia de pesca definitiva. 10 horas en aguas profundas del Pacífico buscando las piezas grandes: marlín, atún aleta amarilla, dorado, wahoo. Equipo profesional de altura en un yate de 39 pies con todas las comodidades.",
    includes: ["Yate Sthamas 39'", "Equipo de pesca de altura", "Carnada premium", "Capitán y tripulación", "A/C", "Agua, hielo", "BBQ"],
    notIncludes: ["Bebidas alcohólicas", "Comida (BBQ disponible)"],
    whatToBring: ["Bloqueador solar", "Gorra", "Comida para BBQ", "Bebidas", "Medicamento para mareo"],
    highlights: ["10 horas de pesca", "Aguas profundas", "Equipo de altura", "Especies grandes"],
    schedule: "Salida 7:00am, regreso 5:00pm",
    faq: [
      { q: "¿Se puede pescar marlín?", a: "Sí, las aguas del Pacífico panameño son conocidas por marlín, especialmente de enero a abril." },
    ],
  },
  {
    id: "sthamas-ballenas",
    name: "Ballenas en Yate",
    category: "botes-sthamas",
    price: 1253,
    priceType: "per-group",
    duration: "4 horas",
    difficulty: 1,
    maxPax: 12,
    available: "Jul - Oct",
    commission: "10%",
    image: IMAGES.whaleBreach,
    gallery: [IMAGES.whaleBreach, IMAGES.whaleWatching, IMAGES.sunsetCruise],
    location: "Aguas del Pacífico",
    meetingPoint: "Vista Mar, Playa Caracol",
    shortDescription: "Avistamiento de ballenas desde un yate premium. La experiencia VIP.",
    description: "Ver ballenas jorobadas desde la comodidad de un yate de 39 pies con aire acondicionado. 4 horas de navegación con guía especializado en cetáceos. La versión premium del avistamiento de ballenas.",
    includes: ["Yate Sthamas 39'", "Guía de cetáceos", "Binoculares", "A/C", "Agua, hielo", "WiFi"],
    notIncludes: ["Bebidas alcohólicas", "Comida"],
    whatToBring: ["Cámara con zoom", "Bloqueador solar", "Ropa cómoda"],
    highlights: ["Yate premium", "Guía especializado", "A/C y comodidad", "Hasta 12 personas"],
    schedule: "Salida 8:00am, regreso 12:00pm",
    faq: [
      { q: "¿Mejor que en bote pequeño?", a: "Más cómodo, más estable, con A/C para descansar entre avistamientos." },
    ],
  },
];

// ============================================================
// BOTES RAMPAGE 31' (6 tours)
// ============================================================
export const RAMPAGE_TOURS: Tour[] = [
  {
    id: "rampage-sunset",
    name: "Caracol Sunset Cruise",
    category: "botes-rampage",
    price: 603,
    priceType: "per-group",
    duration: "3 horas",
    difficulty: 1,
    maxPax: 10,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.sunsetCruise,
    gallery: [IMAGES.sunsetCruise, IMAGES.beachAerial],
    location: "Costa de Playa Caracol",
    meetingPoint: "Vista Mar, Playa Caracol",
    shortDescription: "Atardecer en bote deportivo. La opción accesible para un sunset inolvidable.",
    description: "El mismo atardecer espectacular del Pacífico, en un bote deportivo de 31 pies. Más íntimo, más deportivo, igual de inolvidable. Incluye cama, BBQ, agua y hielo.",
    includes: ["Bote Rampage 31'", "Capitán", "Cama", "BBQ", "Agua, hielo"],
    notIncludes: ["Bebidas alcohólicas", "Comida"],
    whatToBring: ["Bebidas", "Comida para BBQ", "Cámara"],
    highlights: ["Precio más accesible", "Hasta 10 personas", "BBQ a bordo", "Atardecer del Pacífico"],
    schedule: "Salida 4:00pm, regreso 7:00pm",
    faq: [{ q: "¿Diferencia con el Sthamas?", a: "El Rampage es más deportivo y compacto. No tiene A/C ni WiFi, pero es más económico." }],
  },
  {
    id: "rampage-party",
    name: "Sail Away Party",
    category: "botes-rampage",
    price: 733,
    priceType: "per-group",
    duration: "3 horas",
    difficulty: 1,
    maxPax: 10,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.sunsetCruise,
    gallery: [IMAGES.sunsetCruise, IMAGES.beachAerial],
    location: "Costa de Playa Caracol",
    meetingPoint: "Vista Mar, Playa Caracol",
    shortDescription: "Fiesta en bote deportivo. Tu celebración sobre el Pacífico.",
    description: "Tu fiesta privada en un bote de 31 pies. Hasta 10 invitados, 3 horas de celebración sobre el agua. BBQ, música y el Pacífico como escenario.",
    includes: ["Bote Rampage 31'", "Capitán", "BBQ", "Agua, hielo", "Sonido"],
    notIncludes: ["Bebidas", "Comida", "Decoración especial"],
    whatToBring: ["Bebidas", "Comida", "Decoración si deseas"],
    highlights: ["Fiesta privada", "Hasta 10 personas", "BBQ", "Más económico"],
    schedule: "Horario flexible",
    faq: [],
  },
  {
    id: "rampage-daypass",
    name: "Day Pass Boná y Otoque",
    category: "botes-rampage",
    price: 1773,
    priceType: "per-group",
    duration: "8 horas",
    difficulty: 1,
    maxPax: 10,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.islaBonaCoast,
    gallery: [IMAGES.islaBonaCoast, IMAGES.islaOtoque, IMAGES.fishingBoat],
    location: "Islas Boná y Otoque",
    meetingPoint: "Vista Mar, Playa Caracol",
    shortDescription: "Día completo en las islas en bote deportivo. Aventura a precio accesible.",
    description: "8 horas explorando las islas Boná y Otoque en bote deportivo. Snorkel, playa virgen, BBQ a bordo. La misma aventura, en formato más deportivo y económico.",
    includes: ["Bote Rampage 31'", "Capitán", "BBQ", "Agua, hielo", "Equipo de snorkel"],
    notIncludes: ["Bebidas", "Comida"],
    whatToBring: ["Comida", "Bebidas", "Bloqueador solar", "Toalla"],
    highlights: ["8 horas", "Islas vírgenes", "Snorkel", "Precio accesible"],
    schedule: "Salida 8:00am, regreso 4:00-6:00pm",
    faq: [],
  },
  {
    id: "rampage-fun-fishing",
    name: "Fun Fishing",
    category: "botes-rampage",
    price: 1318,
    priceType: "per-group",
    duration: "6 horas",
    difficulty: 2,
    maxPax: 10,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.fishingBoat,
    gallery: [IMAGES.fishingBoat, IMAGES.fishingCatch, IMAGES.fishingSport],
    location: "Aguas del Pacífico",
    meetingPoint: "Vista Mar, Playa Caracol",
    shortDescription: "Pesca deportiva en bote de 31 pies. 6 horas de acción a precio accesible.",
    description: "Pesca deportiva en el Rampage 31'. 6 horas en aguas ricas del Pacífico con equipo profesional. La opción deportiva para grupos que quieren pescar sin el precio premium.",
    includes: ["Bote Rampage 31'", "Equipo de pesca", "Carnada", "Capitán", "Agua, hielo"],
    notIncludes: ["Bebidas", "Comida"],
    whatToBring: ["Bloqueador solar", "Comida", "Bebidas"],
    highlights: ["6 horas de pesca", "Equipo profesional", "Precio accesible"],
    schedule: "Salida 7:00am, regreso 1:00pm",
    faq: [],
  },
  {
    id: "rampage-pro-fishing",
    name: "Pro Fishing",
    category: "botes-rampage",
    price: 2163,
    priceType: "per-group",
    duration: "10 horas",
    difficulty: 3,
    maxPax: 10,
    available: "Todo el año",
    commission: "10%",
    image: IMAGES.fishingSport,
    gallery: [IMAGES.fishingSport, IMAGES.fishingCatch, IMAGES.fishingBoat],
    location: "Aguas profundas del Pacífico",
    meetingPoint: "Vista Mar, Playa Caracol",
    shortDescription: "Pesca de altura en bote deportivo. 10 horas para los que van en serio.",
    description: "10 horas de pesca de altura en el Rampage 31'. Aguas profundas, especies grandes, equipo profesional. Para pescadores que quieren la experiencia completa a un precio más accesible.",
    includes: ["Bote Rampage 31'", "Equipo de altura", "Carnada premium", "Capitán", "Agua, hielo"],
    notIncludes: ["Bebidas", "Comida"],
    whatToBring: ["Bloqueador solar", "Comida", "Bebidas", "Medicamento para mareo"],
    highlights: ["10 horas", "Aguas profundas", "Equipo de altura", "Precio accesible"],
    schedule: "Salida 7:00am, regreso 5:00pm",
    faq: [],
  },
  {
    id: "rampage-ballenas",
    name: "Ballenas",
    category: "botes-rampage",
    price: 863,
    priceType: "per-group",
    duration: "4 horas",
    difficulty: 1,
    maxPax: 10,
    available: "Jul - Oct",
    commission: "10%",
    image: IMAGES.whaleWatching,
    gallery: [IMAGES.whaleWatching, IMAGES.whaleBreach, IMAGES.fishingBoat],
    location: "Aguas del Pacífico",
    meetingPoint: "Vista Mar, Playa Caracol",
    shortDescription: "Avistamiento de ballenas en bote deportivo. La experiencia a precio accesible.",
    description: "Ballenas jorobadas desde un bote deportivo de 31 pies. 4 horas de navegación con guía especializado. Más íntimo y deportivo que el yate, a un precio más accesible.",
    includes: ["Bote Rampage 31'", "Guía de cetáceos", "Binoculares", "Agua, hielo"],
    notIncludes: ["Bebidas", "Comida"],
    whatToBring: ["Cámara", "Bloqueador solar", "Ropa cómoda"],
    highlights: ["Precio accesible", "Guía especializado", "Hasta 10 personas"],
    schedule: "Salida 8:00am, regreso 12:00pm",
    faq: [],
  },
];

// ============================================================
// ECO ADVENTURES (10 tours) — antes "Terrestres"
// ============================================================
export const ECO_ADVENTURES: Tour[] = [
  {
    id: "hiking-cerro-chame",
    name: "Hiking Cerro Chame",
    category: "eco-adventures",
    price: 25,
    priceType: "per-person",
    duration: "5 horas",
    difficulty: 4,
    maxPax: 15,
    minPax: 2,
    available: "Dic - Abr",
    commission: "20%",
    image: IMAGES.cerroChameHike,
    gallery: [IMAGES.cerroChameHike, IMAGES.cerroChame, IMAGES.beachAerial],
    location: "Cerro Chame",
    meetingPoint: "Playa Caracol",
    shortDescription: "Sube al Cerro Chame y contempla el Pacífico desde 560 metros. Vista de 360 grados.",
    description: "El Cerro Chame es el guardián de la costa. A 560 metros sobre el nivel del mar, ofrece una vista de 360 grados que abarca desde Ciudad de Panamá hasta las islas del Pacífico. El sendero es desafiante pero la recompensa es incomparable. Ideal para amanecer.",
    includes: ["Transporte ida/vuelta desde Playa Caracol", "Guía certificado", "Entrada", "Agua"],
    notIncludes: ["Alimentación", "Equipo de hiking personal"],
    whatToBring: ["Zapatos de hiking", "Ropa deportiva", "Bloqueador solar", "2 litros de agua mínimo", "Snack energético", "Linterna (si es amanecer)"],
    highlights: ["Vista 360° del Pacífico", "560 metros de altura", "Amanecer épico", "Desafío físico"],
    faq: [
      { q: "¿Qué tan difícil es?", a: "Moderado-alto. Se requiere condición física. El ascenso toma ~2.5 horas." },
      { q: "¿Se puede hacer al amanecer?", a: "Sí, es la mejor hora. Salimos a las 4:30am para llegar a la cima con la primera luz." },
    ],
  },
  {
    id: "laguna-san-carlos",
    name: "Day Pass Laguna San Carlos",
    category: "eco-adventures",
    price: 50,
    priceType: "per-person",
    duration: "3 horas",
    difficulty: 1,
    maxPax: 15,
    minPax: 4,
    available: "Dic - Abr",
    commission: "20%",
    image: IMAGES.valleAntonPool,
    gallery: [IMAGES.valleAntonPool, IMAGES.cascadaChame],
    location: "Laguna San Carlos",
    meetingPoint: "Playa Caracol",
    shortDescription: "Un oasis de agua dulce rodeado de montañas. Relax total en la naturaleza.",
    description: "La Laguna San Carlos es un espejo de agua dulce rodeado de montañas verdes. Un lugar perfecto para desconectar, nadar en aguas frescas y disfrutar de la naturaleza panameña lejos del mar.",
    includes: ["Transporte ida/vuelta", "Guía", "Entrada", "Agua"],
    notIncludes: ["Alimentación", "Equipo de natación"],
    whatToBring: ["Traje de baño", "Toalla", "Bloqueador solar", "Snacks"],
    highlights: ["Agua dulce cristalina", "Rodeado de montañas", "Relax total", "Naturaleza pura"],
    faq: [{ q: "¿Se puede nadar?", a: "Sí, la laguna tiene zonas seguras para nadar." }],
  },
  {
    id: "cascada-filipinas",
    name: "Tour Cascada Filipinas",
    category: "eco-adventures",
    price: 50,
    priceType: "per-person",
    duration: "3 horas",
    difficulty: 2,
    maxPax: 15,
    minPax: 4,
    available: "Dic - Abr",
    commission: "20%",
    image: IMAGES.cascadaFilipinas,
    gallery: [IMAGES.cascadaFilipinas, IMAGES.cascadaChame, IMAGES.cascadaCanyon],
    location: "Cascada Filipinas, Chame",
    meetingPoint: "Playa Caracol",
    shortDescription: "Cascada escondida en la selva de Chame. Caminata y baño en agua cristalina.",
    description: "La Cascada Filipinas es una joya escondida en la selva de Chame. Una caminata de dificultad moderada te lleva hasta una cascada de agua cristalina donde puedes bañarte rodeado de naturaleza virgen. El sonido del agua cayendo y el verde intenso de la selva crean una experiencia sensorial única.",
    includes: ["Transporte ida/vuelta", "Guía local", "Entrada", "Agua"],
    notIncludes: ["Alimentación"],
    whatToBring: ["Zapatos para agua o hiking", "Traje de baño", "Toalla", "Bloqueador solar", "Repelente", "Snack"],
    highlights: ["Cascada cristalina", "Selva virgen", "Baño natural", "Caminata moderada"],
    faq: [
      { q: "¿Se puede bañar en la cascada?", a: "Sí, hay una poza natural perfecta para nadar." },
      { q: "¿Qué tan lejos está de Playa Caracol?", a: "Aproximadamente 30 minutos en vehículo + 20 minutos de caminata." },
    ],
  },
  {
    id: "cascadas-manglarito",
    name: "Tour Cascadas Manglarito",
    category: "eco-adventures",
    price: 50,
    priceType: "per-person",
    duration: "3 horas",
    difficulty: 2,
    maxPax: 15,
    minPax: 4,
    available: "Dic - Abr",
    commission: "20%",
    image: IMAGES.cascadaChame,
    gallery: [IMAGES.cascadaChame, IMAGES.cascadaFilipinas, IMAGES.cascadaCanyon],
    location: "Manglarito, Chame",
    meetingPoint: "Playa Caracol",
    shortDescription: "Cascadas en serie rodeadas de manglar y selva. Una aventura acuática natural.",
    description: "Las cascadas de Manglarito son una serie de caídas de agua en medio de la selva. Cada una con su propia poza para nadar. Una caminata que combina aventura, naturaleza y refrescantes baños naturales.",
    includes: ["Transporte ida/vuelta", "Guía local", "Entrada", "Agua"],
    notIncludes: ["Alimentación"],
    whatToBring: ["Zapatos para agua", "Traje de baño", "Toalla", "Repelente", "Snack"],
    highlights: ["Múltiples cascadas", "Pozas naturales", "Selva tropical", "Aventura acuática"],
    faq: [],
  },
  {
    id: "cascada-la-gloria",
    name: "Tour Cascada La Gloria",
    category: "eco-adventures",
    price: 75,
    priceType: "per-person",
    duration: "3 horas",
    difficulty: 3,
    maxPax: 15,
    minPax: 4,
    available: "Dic - Abr",
    commission: "20%",
    image: IMAGES.cascadaCanyon,
    gallery: [IMAGES.cascadaCanyon, IMAGES.cascadaFilipinas, IMAGES.cascadaChame],
    location: "La Gloria, Chame",
    meetingPoint: "Playa Caracol",
    shortDescription: "La cascada más impresionante de Chame. Cañón de roca, agua turquesa y aventura.",
    description: "La Cascada La Gloria es la joya de la corona de Chame. Un cañón de roca con agua turquesa que parece sacado de una película. La caminata es más desafiante, pero la recompensa es una de las cascadas más fotogénicas de todo Panamá.",
    includes: ["Transporte ida/vuelta", "Guía experto", "Entrada", "Agua", "Cuerdas de seguridad"],
    notIncludes: ["Alimentación", "Equipo de rappel"],
    whatToBring: ["Zapatos de hiking resistentes al agua", "Traje de baño", "Cámara waterproof", "Snack energético"],
    highlights: ["Cañón de roca", "Agua turquesa", "La más fotogénica", "Aventura real"],
    faq: [
      { q: "¿Qué tan difícil es?", a: "Moderado-alto. Hay secciones con cuerdas y roca resbaladiza." },
    ],
  },
  {
    id: "tour-7-cascadas",
    name: "Tour 7 Cascadas",
    category: "eco-adventures",
    price: 150,
    priceType: "per-person",
    duration: "7 horas",
    difficulty: 4,
    maxPax: 10,
    minPax: 4,
    available: "Dic - Abr",
    commission: "20%",
    image: IMAGES.cascadaFilipinas,
    gallery: [IMAGES.cascadaFilipinas, IMAGES.cascadaCanyon, IMAGES.cascadaChame, IMAGES.cerroChameHike],
    location: "Chame",
    meetingPoint: "Playa Caracol",
    shortDescription: "La aventura definitiva: 7 cascadas en un día. Para los que quieren vivirlo todo.",
    description: "El tour más épico de Chame. 7 cascadas en un solo día, cada una diferente, cada una más impresionante que la anterior. 7 horas de caminata, natación, exploración y conexión con la naturaleza más salvaje de Panamá. Solo para aventureros de verdad.",
    includes: ["Transporte ida/vuelta", "Guía experto", "Entrada a todas las cascadas", "Almuerzo de campo", "Agua", "Equipo de seguridad"],
    notIncludes: ["Equipo personal de hiking"],
    whatToBring: ["Zapatos de hiking resistentes al agua", "Traje de baño", "Muda de ropa seca", "Bloqueador solar", "Repelente", "Cámara waterproof"],
    highlights: ["7 cascadas en 1 día", "Almuerzo incluido", "Aventura épica", "Solo para valientes"],
    schedule: "Salida 7:00am, regreso ~2:00pm",
    faq: [
      { q: "¿Qué condición física necesito?", a: "Alta. Son 7 horas de caminata con terreno irregular y subidas." },
      { q: "¿Se puede hacer parcial?", a: "No, el tour es completo. Para opciones más cortas, elige una cascada individual." },
    ],
  },
  {
    id: "rappel-filipinas",
    name: "Rappel Cascada Filipinas",
    category: "eco-adventures",
    price: 120,
    priceType: "per-person",
    duration: "5 horas",
    difficulty: 5,
    maxPax: 8,
    minPax: 4,
    available: "Dic - Abr",
    commission: "5%",
    image: IMAGES.cascadaFilipinas,
    gallery: [IMAGES.cascadaFilipinas, IMAGES.cascadaCanyon],
    location: "Cascada Filipinas, Chame",
    meetingPoint: "Playa Caracol",
    shortDescription: "Desciende la cascada haciendo rappel. Adrenalina extrema en la selva.",
    description: "Para los que buscan adrenalina real. Desciendes la Cascada Filipinas haciendo rappel por la pared de roca mientras el agua cae a tu lado. Equipo profesional, guías certificados y una experiencia que no encontrarás en ningún otro lugar de Panamá.",
    includes: ["Transporte ida/vuelta", "Equipo completo de rappel", "Guía certificado", "Seguro de aventura", "Agua"],
    notIncludes: ["Alimentación", "Fotos profesionales (disponible por costo adicional)"],
    whatToBring: ["Ropa deportiva que se pueda mojar", "Zapatos cerrados resistentes al agua", "Muda de ropa seca"],
    requirements: ["Mayor de 16 años", "Condición física buena", "Sin vértigo severo"],
    highlights: ["Rappel en cascada", "Adrenalina extrema", "Equipo profesional", "Experiencia única"],
    faq: [
      { q: "¿Necesito experiencia en rappel?", a: "No, el guía te enseña todo antes de descender." },
      { q: "¿Es seguro?", a: "Sí, equipo profesional certificado y guías con años de experiencia." },
    ],
  },
  {
    id: "cascada-manantial",
    name: "Cascada Manantial de Vida",
    category: "eco-adventures",
    price: 120,
    priceType: "per-person",
    duration: "6 horas",
    difficulty: 4,
    maxPax: 10,
    minPax: 4,
    available: "Dic - Abr",
    commission: "5%",
    image: IMAGES.cascadaCanyon,
    gallery: [IMAGES.cascadaCanyon, IMAGES.cascadaFilipinas, IMAGES.cascadaChame],
    location: "Chame",
    meetingPoint: "Playa Caracol",
    shortDescription: "Una cascada remota que pocos conocen. El secreto mejor guardado de Chame.",
    description: "Manantial de Vida es una cascada remota que pocos turistas conocen. La caminata de 6 horas te lleva por senderos poco transitados hasta una cascada majestuosa en medio de la selva virgen. Una experiencia para quienes buscan lo auténtico.",
    includes: ["Transporte ida/vuelta", "Guía experto", "Entrada", "Almuerzo de campo", "Agua"],
    notIncludes: ["Equipo personal"],
    whatToBring: ["Zapatos de hiking", "Traje de baño", "Muda seca", "Repelente", "Snacks extra"],
    highlights: ["Cascada remota", "Pocos visitantes", "Selva virgen", "Experiencia auténtica"],
    faq: [],
  },
  {
    id: "valle-de-anton",
    name: "Day Trip El Valle de Antón",
    category: "eco-adventures",
    price: 50,
    priceType: "per-person",
    duration: "6 horas",
    difficulty: 1,
    maxPax: 15,
    minPax: 4,
    available: "Dic - Abr",
    commission: "10%",
    image: IMAGES.valleAntonWaterfall,
    gallery: [IMAGES.valleAntonWaterfall, IMAGES.valleAntonPool, IMAGES.cerroChame],
    location: "El Valle de Antón",
    meetingPoint: "Playa Caracol",
    shortDescription: "El pueblo en el cráter de un volcán. Cascadas, mercado artesanal y naturaleza.",
    description: "El Valle de Antón es un pueblo mágico ubicado dentro del cráter de un volcán extinto. Cascadas, aguas termales, mercado artesanal, aves exóticas y un clima fresco de montaña. Un día completo de exploración cultural y natural a solo 1 hora de Playa Caracol.",
    includes: ["Transporte ida/vuelta", "Guía", "Entrada a cascada", "Agua"],
    notIncludes: ["Alimentación", "Compras en mercado artesanal", "Aguas termales (costo adicional)"],
    whatToBring: ["Ropa cómoda", "Chaqueta ligera (clima fresco)", "Cámara", "Efectivo para mercado"],
    highlights: ["Cráter de volcán", "Cascadas y aguas termales", "Mercado artesanal", "Aves exóticas"],
    faq: [
      { q: "¿Qué tan lejos está?", a: "Aproximadamente 1 hora en vehículo desde Playa Caracol." },
      { q: "¿Hace frío?", a: "El clima es fresco (18-24°C), lleva una chaqueta ligera." },
    ],
  },
  {
    id: "rafting-tubing-cajones",
    name: "Rafting Tubing Cajones",
    category: "eco-adventures",
    price: 50,
    priceType: "per-person",
    duration: "3 horas",
    difficulty: 3,
    maxPax: 15,
    minPax: 4,
    available: "Todo el año",
    commission: "20%",
    image: IMAGES.tubingRiver,
    gallery: [IMAGES.tubingRiver, IMAGES.tubingGroup, IMAGES.cascadaCanyon],
    location: "Río Cajones",
    meetingPoint: "Playa Caracol",
    shortDescription: "Baja el río en tubing. Rápidos, pozas y diversión acuática en la selva.",
    description: "Baja el Río Cajones en un tubing inflable. Rápidos clase II-III, pozas cristalinas para descansar, y la selva tropical como escenario. Una aventura acuática que combina adrenalina con naturaleza. Disponible todo el año.",
    includes: ["Transporte ida/vuelta", "Tubing inflable", "Casco y chaleco", "Guía de río", "Agua"],
    notIncludes: ["Alimentación", "Fotos"],
    whatToBring: ["Traje de baño", "Zapatos para agua (obligatorio)", "Bloqueador solar waterproof", "Ropa que se pueda mojar"],
    highlights: ["Rápidos clase II-III", "Disponible todo el año", "Selva tropical", "Diversión garantizada"],
    faq: [
      { q: "¿Es peligroso?", a: "No, los rápidos son clase II-III (moderados). Siempre con guía y equipo de seguridad." },
      { q: "¿Niños pueden participar?", a: "Desde 10 años con adulto responsable." },
    ],
  },
];

// ============================================================
// ALL TOURS COMBINED
// ============================================================
export const ALL_TOURS: Tour[] = [
  ...SURF_KITE_TOURS,
  ...ACUATICAS_TOURS,
  ...PREMIUM_TOURS,
  ...STHAMAS_TOURS,
  ...RAMPAGE_TOURS,
  ...ECO_ADVENTURES,
];

// Helper to get tours by category
export function getToursByCategory(categoryId: CategoryId): Tour[] {
  return ALL_TOURS.filter((t) => t.category === categoryId);
}

// Helper to get a single tour by ID
export function getTourById(id: string): Tour | undefined {
  return ALL_TOURS.find((t) => t.id === id);
}

// Helper to get category by ID
export function getCategoryById(id: CategoryId): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

// Difficulty labels
export function getDifficultyLabel(level: number): string {
  const labels = ["", "Fácil", "Moderado", "Desafiante", "Difícil", "Extremo"];
  return labels[level] || "";
}

// Price type labels
export function getPriceTypeLabel(type: string): string {
  switch (type) {
    case "per-person": return "por persona";
    case "per-group": return "por grupo";
    case "per-vehicle": return "por vehículo";
    default: return "";
  }
}
